import { mkdir, writeFile } from 'node:fs/promises';
import { generateCss } from '../src/tokens/tokens.mjs';

const output = 'fixtures/plain/generated-tokens.css';
await mkdir('fixtures/plain', { recursive: true });
await writeFile(output, `/* Generated by scripts/build-tokens.mjs; source: src/tokens/tokens.mjs */\n${generateCss()}`);
console.log(`Generated ${output}`);
