import { mkdir, writeFile } from 'node:fs/promises';
import { generateCss } from '../src/tokens/tokens.mjs';
import { themes } from '../fixtures/inputs.mjs';

const output = 'fixtures/plain/generated-tokens.css';
await mkdir('fixtures/plain', { recursive: true });
await writeFile(output, `/* Generated by scripts/build-tokens.mjs; source: fixtures/inputs.mjs */\n${generateCss(themes)}`);
console.log(`Generated ${output}`);
