import { mkdir, writeFile } from 'node:fs/promises';
import { generateCss } from '../src/tokens/tokens.mjs';
import { exportDtcg, generateThemeManifest, manifestHash } from '../src/tokens/dtcg.mjs';
import { themes } from '../fixtures/inputs.mjs';
import { themeSelectors } from '../fixtures/theme-manifest.mjs';

const cssOutput = 'fixtures/plain/generated-tokens.css';
const dtcgDir = 'generated/dtcg';
const tokenDir = 'generated/tokens';
await mkdir('fixtures/plain', { recursive: true });
await mkdir(dtcgDir, { recursive: true });
await mkdir(tokenDir, { recursive: true });
await writeFile(cssOutput, `/* Generated by scripts/build-tokens.mjs; source: fixtures/inputs.mjs */\n${generateCss(themes, { selectors: themeSelectors })}`);
for (const name of Object.keys(themes).sort()) {
  const one = { [name]: themes[name] };
  await writeFile(`${dtcgDir}/${name}.json`, exportDtcg(one, { selectors: themeSelectors }));
  await writeFile(`${tokenDir}/${name}.css`, `/* Generated token CSS; source: fixtures/inputs.mjs */\n${generateCss(one, { selectors: themeSelectors })}`);
}
const manifest = generateThemeManifest(themes, { selectors: themeSelectors });
manifest.provenance = { generator: 'neobrui-token-exporter/1', source: 'fixtures/inputs.mjs', dtcgVersion: '2025.10', manifestSha256: manifestHash(manifest) };
await writeFile(`${dtcgDir}/manifest.json`, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Generated ${cssOutput}, ${Object.keys(themes).length} token CSS and DTCG artifacts`);
